import { MenuItem, Order } from '@/types/order';

export const mockMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Chicken Sandwich',
    inStock: 12,
    availableToPickUp: 5,
    description: 'Grilled chicken with lettuce, tomato, and mayo',
    price: 4.50,
    category: ['Sandwiches'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: '200g',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '2',
    name: 'Caesar Salad',
    inStock: 16,
    availableToPickUp: 13,
    description: 'Fresh romaine with parmesan and croutons',
    price: 5.00,
    category: ['Salads'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: '100g',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '3',
    name: 'Pepperoni Pizza Slice',
    inStock: 23,
    availableToPickUp: 22,
    description: 'Classic pepperoni on crispy crust',
    price: 3.00,
    category: ['Pizza'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: '4 fatias',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '4',
    name: 'Orange Juice',
    inStock: 42,
    availableToPickUp: 41,
    description: 'Freshly squeezed orange juice',
    price: 2.50,
    category: ['Drinks'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: '400ml',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '5',
    name: 'Chocolate Chip Cookie',
    inStock: 67,
    availableToPickUp: 58,
    description: 'Warm and chewy chocolate chip cookie',
    price: 1.50,
    category: ['Desserts'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: 'Pacote 4 unidades',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '6',
    name: 'Turkey Wrap',
    inStock: 9,
    availableToPickUp: 5,
    description: 'Turkey, cheese, and veggies in a tortilla',
    price: 4.75,
    category: ['Sandwiches'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: '120g',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '7',
    name: 'Fruit Cup',
    inStock: 2,
    availableToPickUp: 0,
    description: 'Mixed seasonal fresh fruits',
    price: 3.50,
    category: ['Healthy'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: 'Copo 250ml',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
  {
    id: '8',
    name: 'Combo Meal',
    inStock: 56,
    availableToPickUp: 35,
    description: 'Sandwich + Drink + Side',
    price: 8.50,
    category: ['Combos', 'Meal'],
    expirationData: '2026-01-12',
    replacementInterval: 12,
    minimumStock: 12,
    specifications: 'faltou criatividade',
    image: '../../public/imgs/refri-image-exemple-lg.png',
    available: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    orderCode: 'A123',
    pickUpTime: '12:45',
    items: [
      { ...mockMenuItems[0], quantity: 1 },
      { ...mockMenuItems[3], quantity: 1 },
    ],
    student: {
      name: 'Emma Johnson'
    },
    status: 'received',
    isPaid: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
    total: 7.00,
  },
  {
    id: '2',
    orderCode: 'B456',
    pickUpTime: '10:25',
    items: [
      { ...mockMenuItems[2], quantity: 2 },
      { ...mockMenuItems[4], quantity: 1 },
    ],
    student: {
      name: 'Liam Smith',
    },
    status: 'notPaid',
    createdAt: new Date(Date.now() - 1000 * 60 * 10),
    total: 7.50,
    isPaid: false,
  },
  {
    id: '3',
    orderCode: 'C789',
    pickUpTime: '11:00',
    items: [
      { ...mockMenuItems[7], quantity: 1 },
    ],
    student: {
      name: 'Sophia Williams',
    },
    status: 'ready',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    total: 8.50,
    isPaid: false,
  },
];

export const categories = [
  'All',
  'Pizza',
  'Salads',
  'Combos',
  'Drinks',
  'Healthy',
  'Desserts',
  'Sandwiches',
];